# Generated by Django 5.2.8 on 2025-11-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_create_memberships_for_existing_companies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, verbose_name='نامک')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر شاخص')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='برچسب\u200cها')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی متا')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('views', models.IntegerField(default=0, verbose_name='بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='companies.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'پست وبلاگ',
                'verbose_name_plural': 'پست\u200cهای وبلاگ',
                'ordering': ['-published_date'],
                'unique_together': {('company', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی متا')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='companies.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'slug')},
            },
        ),
    ]
