# Generated by Django 5.2.8 on 2025-11-30 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی متا')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'صفحه سراسری',
                'verbose_name_plural': 'صفحات سراسری',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
