# Generated by Django 5.2.8 on 2025-12-03 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_create_memberships_for_existing_companies'),
        ('contacts', '0001_initial'),
        ('inventory', '0002_item_sale_price'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=100, verbose_name='شماره حواله')),
                ('pickup_address', models.TextField(verbose_name='آدرس مبدا')),
                ('delivery_address', models.TextField(verbose_name='آدرس مقصد')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن مشتری')),
                ('scheduled_date', models.DateField(verbose_name='تاریخ برنامه\u200cریزی شده')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی شده')),
                ('pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان برداشت')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان تحویل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('assigned', 'تخصیص داده شده'), ('picked_up', 'برداشته شده'), ('in_transit', 'در حال حمل'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('priority', models.IntegerField(default=1, verbose_name='اولویت')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مسافت (کیلومتر)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هزینه ارسال')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='امضا تحویل\u200cگیرنده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='companies.company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='contacts.contact', verbose_name='مشتری')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='sales.salesorder', verbose_name='سفارش فروش')),
            ],
            options={
                'verbose_name': 'حواله',
                'verbose_name_plural': 'حواله\u200cها',
                'ordering': ['-scheduled_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('condition_on_delivery', models.CharField(blank=True, max_length=20, null=True, verbose_name='وضعیت هنگام تحویل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.delivery', verbose_name='حواله')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'کالای حواله',
                'verbose_name_plural': 'کالاهای حواله',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام راننده')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع وسیله نقلیه')),
                ('vehicle_plate', models.CharField(blank=True, max_length=50, null=True, verbose_name='پلاک خودرو')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره گواهینامه')),
                ('status', models.CharField(choices=[('available', 'آماده'), ('busy', 'مشغول'), ('off_duty', 'خارج از خدمت')], default='available', max_length=20, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='companies.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'رانندگان',
                'ordering': ['name'],
                'unique_together': {('company', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255, verbose_name='نام مسیر')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='planned', max_length=20, verbose_name='وضعیت')),
                ('start_location', models.TextField(blank=True, null=True, verbose_name='نقطه شروع')),
                ('end_location', models.TextField(blank=True, null=True, verbose_name='نقطه پایان')),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مسافت کل (کیلومتر)')),
                ('estimated_duration', models.IntegerField(default=0, verbose_name='زمان تخمینی (دقیقه)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_routes', to='companies.company', verbose_name='شرکت')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='delivery.driver', verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'مسیر حمل',
                'verbose_name_plural': 'مسیرهای حمل',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.driver', verbose_name='راننده'),
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('company', 'delivery_number')},
        ),
        migrations.CreateModel(
            name='RouteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='ترتیب در مسیر')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True, verbose_name='زمان تخمینی رسیدن')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='delivery.delivery', verbose_name='حواله')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='delivery.deliveryroute', verbose_name='مسیر')),
            ],
            options={
                'verbose_name': 'حواله در مسیر',
                'verbose_name_plural': 'حواله\u200cها در مسیر',
                'ordering': ['sequence'],
                'unique_together': {('route', 'delivery')},
            },
        ),
    ]
