# Generated by Django 5.2.8 on 2025-11-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_create_memberships_for_existing_companies'),
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=100, verbose_name='شماره فروش')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع جزء')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تخفیف')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مالیات')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع کل')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('transfer', 'انتقال بانکی')], max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('refunded', 'بازگشت داده شده')], default='completed', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='صندوقدار')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sales', to='companies.company', verbose_name='شرکت')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='contacts.contact', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'فروش POS',
                'verbose_name_plural': 'فروش\u200cهای POS',
                'ordering': ['-date'],
                'unique_together': {('company', 'sale_number')},
            },
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('transfer', 'انتقال بانکی')], max_length=20, verbose_name='روش پرداخت')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='مرجع')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.possale', verbose_name='فروش')),
            ],
            options={
                'verbose_name': 'پرداخت POS',
                'verbose_name_plural': 'پرداخت\u200cهای POS',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='POSSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تخفیف')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='جمع')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.possale', verbose_name='فروش')),
            ],
            options={
                'verbose_name': 'آیتم فروش POS',
                'verbose_name_plural': 'آیتم\u200cهای فروش POS',
            },
        ),
    ]
