# Generated by Django 5.2.8 on 2025-11-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ برگشتی'),
        ),
        migrations.AddField(
            model_name='possale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='sale_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره فروش'),
        ),
    ]
