# Generated by Django 5.2.8 on 2025-11-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_create_memberships_for_existing_companies'),
        ('contacts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'تماس'), ('meeting', 'جلسه'), ('email', 'ایمیل'), ('task', 'وظیفه')], max_length=20, verbose_name='نوع فعالیت')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='سررسید')),
                ('completed', models.BooleanField(default=False, verbose_name='انجام شده')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اختصاص داده شده به')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='companies.company', verbose_name='شرکت')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='موبایل')),
                ('source', models.CharField(choices=[('website', 'وب\u200cسایت'), ('referral', 'معرفی'), ('cold_call', 'تماس سرد'), ('social_media', 'شبکه\u200cهای اجتماعی'), ('other', 'سایر')], max_length=20, verbose_name='منبع')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شده'), ('qualified', 'واجد شرایط'), ('lost', 'از دست رفته')], default='new', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اختصاص داده شده به')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'سرنخ',
                'verbose_name_plural': 'سرنخ\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ارزش')),
                ('probability', models.IntegerField(default=50, verbose_name='احتمال (%)')),
                ('stage', models.CharField(choices=[('prospecting', 'جستجو'), ('qualification', 'ارزیابی'), ('proposal', 'پیشنهاد'), ('negotiation', 'مذاکره'), ('closed_won', 'بسته شده - برنده'), ('closed_lost', 'بسته شده - بازنده')], default='prospecting', max_length=20, verbose_name='مرحله')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بسته شدن مورد انتظار')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اختصاص داده شده به')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='companies.company', verbose_name='شرکت')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contact', verbose_name='مخاطب')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead', verbose_name='سرنخ')),
            ],
            options={
                'verbose_name': 'فرصت',
                'verbose_name_plural': 'فرصت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
