# Generated by Django 5.2.8 on 2025-11-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت فروش'),
        ),
    ]
