# Generated by Django 5.2.8 on 2025-11-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_create_memberships_for_existing_companies'),
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='شماره فاکتور')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('due_date', models.DateField(verbose_name='سررسید')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('paid', 'پرداخت شده'), ('overdue', 'سررسید گذشته'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع جزء')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تخفیف')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مالیات')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع کل')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ پرداخت شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contacts.contact', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تخفیف')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='جمع')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice', verbose_name='فاکتور')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=100, verbose_name='شماره پیش\u200cفاکتور')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('valid_until', models.DateField(verbose_name='اعتبار تا')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع جزء')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تخفیف')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مالیات')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع کل')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='شرایط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='companies.company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='contacts.contact', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پیش\u200cفاکتور',
                'verbose_name_plural': 'پیش\u200cفاکتورها',
                'ordering': ['-date'],
                'unique_together': {('company', 'quote_number')},
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تخفیف')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='جمع')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation', verbose_name='پیش\u200cفاکتور')),
            ],
            options={
                'verbose_name': 'آیتم پیش\u200cفاکتور',
                'verbose_name_plural': 'آیتم\u200cهای پیش\u200cفاکتور',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='شماره سفارش')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('confirmed', 'تایید شده'), ('in_progress', 'در حال انجام'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع جزء')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تخفیف')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مالیات')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع کل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='companies.company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='contacts.contact', verbose_name='مشتری')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.quotation', verbose_name='پیش\u200cفاکتور')),
            ],
            options={
                'verbose_name': 'سفارش فروش',
                'verbose_name_plural': 'سفارش\u200cهای فروش',
                'ordering': ['-date'],
                'unique_together': {('company', 'order_number')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesorder', verbose_name='سفارش فروش'),
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تخفیف')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='جمع')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='سفارش فروش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش فروش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش فروش',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=100, verbose_name='شماره پرداخت')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('transfer', 'انتقال بانکی'), ('cheque', 'چک')], max_length=20, verbose_name='روش پرداخت')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='مرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company', verbose_name='شرکت')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-date'],
                'unique_together': {('company', 'payment_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'invoice_number')},
        ),
    ]
