# Generated by Django 5.2.8 on 2025-11-27 12:53

from django.db import migrations


def create_memberships_for_existing_companies(apps, schema_editor):
    """
    Create CompanyMembership records for all existing companies
    and set active_company for users who don't have one
    """
    Company = apps.get_model('companies', 'Company')
    CompanyMembership = apps.get_model('companies', 'CompanyMembership')
    User = apps.get_model('accounts', 'User')
    
    # Create memberships for all existing companies
    for company in Company.objects.all():
        # Create membership with owner role for the company owner
        CompanyMembership.objects.get_or_create(
            user=company.owner,
            company=company,
            defaults={
                'role': 'owner',
                'is_active': True
            }
        )
        
        # Set as active company if user doesn't have one
        if not company.owner.active_company:
            company.owner.active_company = company
            company.owner.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by deleting all CompanyMembership records
    """
    CompanyMembership = apps.get_model('companies', 'CompanyMembership')
    CompanyMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_company_is_active_and_more'),
        ('accounts', '0002_alter_user_options_user_active_company'),
    ]

    operations = [
        migrations.RunPython(
            create_memberships_for_existing_companies,
            reverse_migration
        ),
    ]

