# Generated by Django 5.2.8 on 2025-11-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_create_memberships_for_existing_companies'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, verbose_name='شماره سفارش خرید')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل مورد انتظار')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('confirmed', 'تایید شده'), ('received', 'دریافت شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع جزء')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مالیات')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هزینه حمل')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='جمع کل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='companies.company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'سفارش خرید',
                'verbose_name_plural': 'سفارش\u200cهای خرید',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت واحد')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='جمع')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='کالا')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder', verbose_name='سفارش خرید')),
            ],
            options={
                'verbose_name': 'آیتم سفارش خرید',
                'verbose_name_plural': 'آیتم\u200cهای سفارش خرید',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, verbose_name='شماره رسید')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_receipts', to='companies.company', verbose_name='شرکت')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='procurement.purchaseorder', verbose_name='سفارش خرید')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='دریافت شده توسط')),
            ],
            options={
                'verbose_name': 'رسید خرید',
                'verbose_name_plural': 'رسیدهای خرید',
                'ordering': ['-date'],
                'unique_together': {('company', 'receipt_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تعداد دریافت شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorderitem', verbose_name='آیتم سفارش خرید')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchasereceipt', verbose_name='رسید')),
            ],
            options={
                'verbose_name': 'آیتم رسید خرید',
                'verbose_name_plural': 'آیتم\u200cهای رسید خرید',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام تامین\u200cکننده')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='فرد تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه مالیاتی')),
                ('payment_terms', models.TextField(blank=True, null=True, verbose_name='شرایط پرداخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='companies.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'تامین\u200cکننده',
                'verbose_name_plural': 'تامین\u200cکنندگان',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier', verbose_name='تامین\u200cکننده'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('company', 'po_number')},
        ),
    ]
